### ISSUE TITLE
ValueError revChat

### ISSUE THREAD

**Issue by abdullahalkakandilli** [pedrorito/ChatGPTSlackBot#5]
ValueError revChat, even though I put the auth details on docker file, still couldn't find the auth details.

**Comment by pedrorito** [comment]
Since yesterday, OpenAI added Cloudflare protections to their API.
We have to update the authentication in this repo to use `session_token` as the preferred method.
In the meantime, refer to the instructions here: https://github.com/acheong08/ChatGPT/wiki/Setup
