### ISSUE TITLE
Docker compose error 

### ISSUE THREAD

**Issue by jtsolana** [pedrorito/ChatGPTSlackBot#6]
Traceback (most recent call last):
chatgptslackbot  |   File "/app/app.py", line 15, in <module>
chatgptslackbot  |     chatbot = Chatbot(ChatGPTConfig, conversation_id=None)
chatgptslackbot  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 116, in __init__
chatgptslackbot  |     self.refresh_session()
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 295, in refresh_session
chatgptslackbot  |     asyncio.run(self.get_cf_cookies())
chatgptslackbot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
chatgptslackbot  |     return runner.run(main)
chatgptslackbot  |            ^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
chatgptslackbot  |     return self._loop.run_until_complete(task)
chatgptslackbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
chatgptslackbot  |     return future.result()
chatgptslackbot  |            ^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 370, in get_cf_cookies
chatgptslackbot  |     browser = await p.chromium.launch(headless=False)
chatgptslackbot  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 12809, in launch
chatgptslackbot  |     await self._impl_obj.launch(
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
chatgptslackbot  |     Browser, from_channel(await self._channel.send("launch", params))
chatgptslackbot  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 44, in send
chatgptslackbot  |     return await self._connection.wrap_api_call(
chatgptslackbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
chatgptslackbot  |     return await cb()
chatgptslackbot  |            ^^^^^^^^^^
chatgptslackbot  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
chatgptslackbot  |     result = next(iter(done)).result()
chatgptslackbot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
chatgptslackbot  | playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1033/chrome-linux/chrome
chatgptslackbot  | ╔════════════════════════════════════════════════════════════╗
chatgptslackbot  | ║ Looks like Playwright was just installed or updated.       ║
chatgptslackbot  | ║ Please run the following command to download new browsers: ║
chatgptslackbot  | ║                                                            ║
chatgptslackbot  | ║     playwright install                                     ║
chatgptslackbot  | ║                                                            ║
chatgptslackbot  | ║ <3 Playwright Team                                         ║
chatgptslackbot  | ╚════════════════════════════════════════════════════════════╝

**Comment by alexmodesto73** [comment]
same error

**Comment by yevgeniyo** [comment]
same

**Comment by l0ginp** [comment]
Guys, I already fixed this issue !
