### ISSUE TITLE
Is there a plan to bring this back now that official API is out?

### ISSUE THREAD

**Issue by Jimmy-Z** [pedrorito/ChatGPTSlackBot#8]
I've seen a discord bot is using that (or at least claims to be):
https://github.com/Zero6992/chatGPT-discord-bot

**Comment by RalphMao** [comment]
Check out this PR: https://github.com/pedrorito/ChatGPTSlackBot/pull/10

Or you can use my forked repo: https://github.com/RalphMao/ChatGPTSlackBot/tree/main

**Comment by pedrorito** [comment]
Solved
